server:
  port: 8888
mybatis:
  mapperLocations: classpath:mapper/*.xml
  configLocation: classpath:config/mybatis-config.xml
db:
  #默认数据源
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/stpnewtest?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Hongkong&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driverClassName: com.mysql.cj.jdbc.Driver

